exp_id: ${exp_id}
pretrained_model: ${pretrained_model}
pretrained: True
num_classes: 2
num_labels: 2
loss_weights:
  g: 0.1
  Q: 0.1
  masking: 1.0
CUDA: True
learning_rate: 2e-5
sampler: weighted


df_path: /root/graduation_thetis/causal-bert-pytorch/input/modelinput/T-boost/Appliances_preprocess_contains_text_t0.8c0.8_1203-T_boost.csv
image_column: "img_path"
confounds_column: "contains_text"
treatments_column: "T_proxy"
outcome_column: "outcome"
file_name: /root/graduation_thetis/causal-bert-pytorch/run/result/[1216]seed_everything_appliances_watch_contains_text_aug_no_maskloss.yaml
description: "??,con:contains_text, treat:??, confound: ??, aug Yes maskloss"



batch_size: ${batch_size}
num_workers: 31
epoch: ${epoch}
seed: ${seed}
augmentation: False
use_mask_loss: True
mask_ratio: 0.1

total_training_steps: ??? 
