exp_id: ${exp_id}
pretrained_model: ${pretrained_model}
pretrained: True
num_classes: 2
num_labels: 2
loss_weights:
  g: 0.1
  Q: 0.1
  masking: 1.0
CUDA: True
learning_rate: 2e-5
sampler: weighted
n_splits: 2


df_path: /root/graduation_thetis/causal-bert-pytorch/input/modelinput/noise-T-boost/Appliance_preprocess_sharpness_ave_t0.8c10_noise0.5_1221-T_boost.csv
image_column: "img_path"
confounds_column: "contains_text"
treatments_column: "T_proxy"
outcome_column: "outcome"
file_name_T: /root/graduation_thetis/causal-bert-pytorch/run/result/[0110]seed_3_appandwatch_sharpness_ave_noise_aug.yaml
file_name_C: /root/graduation_thetis/causal-bert-pytorch/run/result/[0110]seed_3_app_contains_text_noise_aug_.yaml
description: "??,con:contains_text, treat:??, confound: ?? ,noise:Yes,aug: yes"


batch_size: ${batch_size}
num_workers: 0
epoch: ${epoch}
seed: ${seed}
augmentation: True
use_mask_loss: False
mask_ratio: 0.1

total_training_steps: ??? 
