exp_id: ${exp_id}
pretrained_model: ${pretrained_model}
pretrained: True
num_classes: 2
num_labels: 2
loss_weights:
  g: 0.1
  Q: 0.1
  masking: 1.0
CUDA: True
learning_rate: 2e-5
sampler: weighted


#
df_path: /root/graduation_thetis/causal-bert-pytorch/input/Appliances_preprocess_contains_text_1127.csv
image_column: "img_path"
confounds_column: "contains_text"
treatments_column: "T_proxy"
outcome_column: "outcome"
file_name: /root/graduation_thetis/causal-bert-pytorch/run/result/[1127]seed_everything_appliance_contain_text_proxy_none.yaml
description: "seed20種類,T_proxyラベル,T_proxy補正あり,augmentationなし,交絡がcontains_text"



batch_size: ${batch_size}
num_workers: 31
epoch: ${epoch}
seed: ${seed}
augmentation: False
use_mask_loss: False
mask_ratio: 0.1

total_training_steps: ??? 
